import { QueryClientProvider } from "@tanstack/react-query";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { CategoriesPage } from "@/components/categories/categories-page";
import { ApiError } from "@/lib/api-error";
import { createQueryClient } from "@/lib/query-client";
import { useSession } from "@/providers/session-provider";
import { createCategory, listCategories, updateCategory, updateCategoryStatus } from "@/services/categories";
import type { Category } from "@/types/categories";

vi.mock("@/providers/session-provider", () => ({ useSession: vi.fn() }));
vi.mock("@/services/categories", async (original) => ({ ...(await original<typeof import("@/services/categories")>()), listCategories: vi.fn(), createCategory: vi.fn(), updateCategory: vi.fn(), updateCategoryStatus: vi.fn() }));

const category: Category = { id: "c1", organization_id: "o1", name: "Suporte", description: "Atendimento técnico", is_active: true, created_at: "2026-07-14T12:00:00Z", updated_at: "2026-07-14T12:00:00Z" };
const updateSessionUser = vi.fn();
function session(role: "ADMIN" | "MANAGER" = "ADMIN") { return { status: "authenticated" as const, session: { user: { id: "u", name: "Ana", email: "ana@example.com", avatar_url: null, is_active: true }, organization: { id: "o1", name: "Org", slug: "org" }, membership: { id: "m", role, is_active: true } }, signIn: vi.fn(), signOut: vi.fn(), clearSession: vi.fn(), updateSessionUser }; }
function setup() { const client = createQueryClient(); client.setDefaultOptions({ queries: { retry: false }, mutations: { retry: false } }); return { client, ...render(<QueryClientProvider client={client}><CategoriesPage /></QueryClientProvider>) }; }
async function fill(name = "Financeiro", description = "Contas e pagamentos") { fireEvent.click(screen.getByRole("button", { name: "Nova categoria" })); fireEvent.change(screen.getByLabelText("Nome"), { target: { value: name } }); fireEvent.change(screen.getByLabelText("Descrição"), { target: { value: description } }); }

describe("gerenciamento de categorias", () => {
  beforeEach(() => { vi.mocked(useSession).mockReturnValue(session()); vi.mocked(listCategories).mockReset(); vi.mocked(listCategories).mockResolvedValue([category]); vi.mocked(createCategory).mockReset(); vi.mocked(updateCategory).mockReset(); vi.mocked(updateCategoryStatus).mockReset(); vi.stubGlobal("confirm", vi.fn(() => true)); });
  afterEach(() => { cleanup(); vi.unstubAllGlobals(); });

  it("permite acesso ao administrador", async () => { setup(); expect(await screen.findByRole("heading", { name: "Categorias" })).toBeDefined(); expect(listCategories).toHaveBeenCalled(); });
  it("bloqueia outro papel sem consultar categorias inativas", () => { vi.mocked(useSession).mockReturnValue(session("MANAGER")); setup(); expect(screen.getByRole("alert").textContent).toContain("Apenas administradores"); expect(listCategories).not.toHaveBeenCalled(); });
  it("lista campos e usa o contrato administrativo", async () => { setup(); expect(await screen.findByText("Suporte")).toBeDefined(); expect(screen.getByText("Atendimento técnico")).toBeDefined(); expect(screen.getByText("Ativa")).toBeDefined(); expect(screen.getByText("14/07/2026")).toBeDefined(); expect(listCategories).toHaveBeenCalledWith(expect.any(AbortSignal)); });
  it("exibe loading e estado vazio", async () => { vi.mocked(listCategories).mockReturnValueOnce(new Promise(() => undefined)); const first = setup(); expect(screen.getByRole("status", { name: "Carregando categorias" })).toBeDefined(); first.unmount(); vi.mocked(listCategories).mockResolvedValueOnce([]); setup(); expect(await screen.findByText("Nenhuma categoria encontrada")).toBeDefined(); });
  it("cria categoria normalizando descrição vazia para null", async () => { const created = { ...category, id: "c2", name: "Financeiro", description: null }; vi.mocked(createCategory).mockResolvedValue(created); setup(); await screen.findByText("Suporte"); await fill("Financeiro", ""); fireEvent.click(screen.getByRole("button", { name: "Salvar categoria" })); await waitFor(() => expect(createCategory).toHaveBeenCalledWith({ name: "Financeiro", description: null })); expect(await screen.findByText("Categoria Financeiro criada.")).toBeDefined(); });
  it("trata duplicidade no nome", async () => { vi.mocked(createCategory).mockRejectedValue(new ApiError({ status: 409, code: "category_already_exists", message: "duplicada" })); setup(); await screen.findByText("Suporte"); await fill("Suporte"); fireEvent.click(screen.getByRole("button", { name: "Salvar categoria" })); expect((await screen.findAllByText("Já existe uma categoria com este nome.")).length).toBeGreaterThan(0); });
  it("edita nome e descrição", async () => { const edited = { ...category, name: "Suporte Premium", description: "Prioridade" }; vi.mocked(updateCategory).mockResolvedValue(edited); setup(); await screen.findByText("Suporte"); fireEvent.click(screen.getByRole("button", { name: "Editar" })); fireEvent.change(screen.getByLabelText("Nome"), { target: { value: "Suporte Premium" } }); fireEvent.change(screen.getByLabelText("Descrição"), { target: { value: "Prioridade" } }); fireEvent.click(screen.getByRole("button", { name: "Salvar categoria" })); await waitFor(() => expect(updateCategory).toHaveBeenCalledWith("c1", { name: "Suporte Premium", description: "Prioridade" })); expect(await screen.findByText("Categoria Suporte Premium atualizada.")).toBeDefined(); });
  it("desativa sem exclusão física e com confirmação", async () => { vi.mocked(updateCategoryStatus).mockResolvedValue({ ...category, is_active: false }); setup(); await screen.findByText("Suporte"); fireEvent.click(screen.getByRole("button", { name: "Desativar" })); expect(confirm).toHaveBeenCalledWith("Deseja desativar a categoria Suporte?"); expect(await screen.findByText("Categoria Suporte desativada.")).toBeDefined(); expect(screen.getByText("Inativa")).toBeDefined(); });
  it("ativa categoria inativa", async () => { const inactive = { ...category, is_active: false }; vi.mocked(listCategories).mockResolvedValue([inactive]); vi.mocked(updateCategoryStatus).mockResolvedValue(category); setup(); await screen.findByText("Inativa"); fireEvent.click(screen.getByRole("button", { name: "Ativar" })); expect(await screen.findByText("Categoria Suporte ativada.")).toBeDefined(); });
  it("atualiza o cache após edição", async () => { const edited = { ...category, name: "Novo Suporte" }; vi.mocked(updateCategory).mockResolvedValue(edited); const { client } = setup(); await screen.findByText("Suporte"); fireEvent.click(screen.getByRole("button", { name: "Editar" })); fireEvent.change(screen.getByLabelText("Nome"), { target: { value: "Novo Suporte" } }); fireEvent.click(screen.getByRole("button", { name: "Salvar categoria" })); await waitFor(() => expect(client.getQueryData<Category[]>(["categories"])?.[0].name).toBe("Novo Suporte")); });
  it("exibe erro de listagem e permite tentar novamente", async () => { vi.mocked(listCategories).mockRejectedValue(new Error("falha")); setup(); expect((await screen.findByRole("alert")).textContent).toContain("Não foi possível carregar"); expect(screen.getByRole("button", { name: "Tentar novamente" })).toBeDefined(); });
  it("oferece busca e filtro de status sobre a lista completa", async () => { vi.mocked(listCategories).mockResolvedValue([category, { ...category, id: "c2", name: "Financeiro", is_active: false }]); setup(); await screen.findByText("Financeiro"); fireEvent.change(screen.getByLabelText("Buscar categorias"), { target: { value: "suporte" } }); expect(screen.queryByText("Financeiro")).toBeNull(); fireEvent.change(screen.getByLabelText("Buscar categorias"), { target: { value: "" } }); fireEvent.change(screen.getByLabelText("Filtrar por status"), { target: { value: "inactive" } }); expect(screen.queryByText("Suporte")).toBeNull(); expect(screen.getByText("Financeiro")).toBeDefined(); });
});
