"use client";

import { useQuery } from "@tanstack/react-query";
import Link from "next/link";
import { Cell, Legend, Pie, PieChart, ResponsiveContainer, Tooltip } from "recharts";
import { TicketPriorityBadge, TicketStatusBadge } from "@/components/tickets/ticket-badges";
import { TicketAssignee } from "@/components/tickets/ticket-assignee";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { formatDateTime, formatDueDate, formatOverdue, translateTicketPriority, translateTicketStatus } from "@/lib/ticket-formatters";
import { useSession } from "@/providers/session-provider";
import { dashboardOverdueQueryKey, dashboardPriorityQueryKey, dashboardRecentQueryKey, dashboardStatusQueryKey, getDashboardOverdue, getDashboardPriorityDistribution, getDashboardRecent, getDashboardStatusDistribution } from "@/services/dashboard";
import type { DashboardOverdueTicket, DashboardTicket, PriorityDistributionItem, StatusDistributionItem } from "@/types/dashboard";

const statusColors = ["#64748b", "#2563eb", "#d97706", "#059669", "#dc2626"];
const priorityColors = ["#64748b", "#2563eb", "#ea580c", "#dc2626"];

function Block({ title, children }: { title: string; children: React.ReactNode }) { return <section aria-labelledby={`dashboard-${title.toLowerCase().replaceAll(" ", "-")}`} className="min-w-0 rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><h2 className="text-lg font-bold text-slate-950" id={`dashboard-${title.toLowerCase().replaceAll(" ", "-")}`}>{title}</h2><div className="mt-4">{children}</div></section>; }
function BlockError({ retry }: { retry: () => void }) { return <div className="rounded-lg border border-red-200 bg-red-50 p-4" role="alert"><p className="text-sm text-red-800">Não foi possível carregar este bloco.</p><Button className="mt-3" onClick={retry} type="button" variant="secondary">Tentar novamente</Button></div>; }
function Empty({ message }: { message: string }) { return <p className="rounded-lg border border-dashed border-slate-300 p-5 text-center text-sm text-slate-600">{message}</p>; }

type ChartItem = { key: string; name: string; value: number };
function AccessiblePie({ title, data, colors }: { title: string; data: ChartItem[]; colors: string[] }) {
  return <div><div aria-hidden="true" className="h-64 w-full"><ResponsiveContainer height="100%" width="100%"><PieChart><Pie data={data} dataKey="value" innerRadius={45} nameKey="name" outerRadius={80} paddingAngle={2}>{data.map((item, index) => <Cell fill={colors[index]} key={item.key} />)}</Pie><Tooltip formatter={(value) => [`${value} solicitações`, "Quantidade"]} /><Legend /></PieChart></ResponsiveContainer></div><table className="mt-3 w-full text-sm"><caption className="sr-only">Alternativa textual para {title}</caption><thead><tr className="border-b border-slate-200 text-left text-slate-600"><th className="py-2 font-medium">{title}</th><th className="py-2 text-right font-medium">Quantidade</th></tr></thead><tbody>{data.map((item, index) => <tr className="border-b border-slate-100 last:border-0" key={item.key}><td className="py-2"><span aria-hidden="true" className="mr-2 inline-block size-2 rounded-full" style={{ backgroundColor: colors[index] }} />{item.name}</td><td className="py-2 text-right font-semibold">{item.value}</td></tr>)}</tbody></table></div>;
}

function StatusChart({ enabled }: { enabled: boolean }) { const query = useQuery({ queryKey: dashboardStatusQueryKey, queryFn: ({ signal }) => getDashboardStatusDistribution(signal), enabled }); if (!enabled) return null; return <Block title="Solicitações por status">{query.isPending ? <Skeleton label="Carregando gráfico por status" lines={6} /> : query.isError ? <BlockError retry={() => { void query.refetch(); }} /> : <AccessiblePie colors={statusColors} data={query.data.map((item: StatusDistributionItem) => ({ key: item.status, name: translateTicketStatus(item.status), value: item.count }))} title="Status" />}</Block>; }
function PriorityChart({ enabled }: { enabled: boolean }) { const query = useQuery({ queryKey: dashboardPriorityQueryKey, queryFn: ({ signal }) => getDashboardPriorityDistribution(signal), enabled }); if (!enabled) return null; return <Block title="Solicitações por prioridade">{query.isPending ? <Skeleton label="Carregando gráfico por prioridade" lines={6} /> : query.isError ? <BlockError retry={() => { void query.refetch(); }} /> : <AccessiblePie colors={priorityColors} data={query.data.map((item: PriorityDistributionItem) => ({ key: item.priority, name: translateTicketPriority(item.priority), value: item.count }))} title="Prioridade" />}</Block>; }

function RecentItem({ ticket }: { ticket: DashboardTicket }) { return <li className="py-4 first:pt-0 last:pb-0"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><Link className="break-words font-semibold text-indigo-700 hover:underline focus-visible:outline-2 focus-visible:outline-indigo-600" href={`/solicitacoes/${ticket.id}`}>{ticket.title}</Link><div className="mt-2 flex flex-wrap gap-2"><TicketStatusBadge status={ticket.status} /><TicketPriorityBadge priority={ticket.priority} /></div></div><time className="shrink-0 text-xs text-slate-500" dateTime={ticket.created_at}>{formatDateTime(ticket.created_at)}</time></div><div className="mt-3"><TicketAssignee assignee={ticket.assignee} compact /></div></li>; }
function OverdueItem({ ticket }: { ticket: DashboardOverdueTicket }) { return <li className="py-4 first:pt-0 last:pb-0"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><Link className="break-words font-semibold text-indigo-700 hover:underline focus-visible:outline-2 focus-visible:outline-indigo-600" href={`/solicitacoes/${ticket.id}`}>{ticket.title}</Link><div className="mt-2 flex flex-wrap items-center gap-2"><TicketPriorityBadge priority={ticket.priority} /><span className="text-sm font-semibold text-red-700">{formatOverdue(ticket.overdue_seconds)}</span></div></div><span className="shrink-0 text-xs text-slate-500">{formatDueDate(ticket.due_date)}</span></div><div className="mt-3"><TicketAssignee assignee={ticket.assignee} compact /></div></li>; }
function RecentList({ enabled }: { enabled: boolean }) { const query = useQuery({ queryKey: dashboardRecentQueryKey, queryFn: ({ signal }) => getDashboardRecent(signal), enabled }); if (!enabled) return null; return <Block title="Solicitações recentes">{query.isPending ? <Skeleton label="Carregando solicitações recentes" lines={6} /> : query.isError ? <BlockError retry={() => { void query.refetch(); }} /> : query.data.length === 0 ? <Empty message="Nenhuma solicitação recente." /> : <ol aria-label="Solicitações recentes em ordem do backend" className="divide-y divide-slate-200">{query.data.map((ticket) => <RecentItem key={ticket.id} ticket={ticket} />)}</ol>}</Block>; }
function OverdueList({ enabled }: { enabled: boolean }) { const query = useQuery({ queryKey: dashboardOverdueQueryKey, queryFn: ({ signal }) => getDashboardOverdue(signal), enabled }); if (!enabled) return null; return <Block title="Maiores atrasos">{query.isPending ? <Skeleton label="Carregando maiores atrasos" lines={6} /> : query.isError ? <BlockError retry={() => { void query.refetch(); }} /> : query.data.length === 0 ? <Empty message="Nenhuma solicitação atrasada." /> : <ol aria-label="Maiores atrasos em ordem do backend" className="divide-y divide-slate-200">{query.data.map((ticket) => <OverdueItem key={ticket.id} ticket={ticket} />)}</ol>}</Block>; }

export function DashboardDetails() { const { session } = useSession(); const enabled = session?.membership.role === "ADMIN" || session?.membership.role === "MANAGER"; return <div className="space-y-6"><div className="grid gap-6 lg:grid-cols-2"><StatusChart enabled={enabled} /><PriorityChart enabled={enabled} /></div><div className="grid gap-6 lg:grid-cols-2"><RecentList enabled={enabled} /><OverdueList enabled={enabled} /></div></div>; }
