import { TicketAssignee } from "@/components/tickets/ticket-assignee";
import { TicketPriorityBadge, TicketStatusBadge } from "@/components/tickets/ticket-badges";
import { formatDateTime, formatDueDate, formatOverdue } from "@/lib/ticket-formatters";
import type { TicketCardData } from "@/types/tickets";

export function TicketCard({ ticket, action, showRequester = true }: { ticket: TicketCardData; action?: ReactNode; showRequester?: boolean }) {
  return <article className="flex h-full min-w-0 flex-col rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5" data-testid="ticket-card"><div className="flex flex-wrap items-center gap-2"><TicketStatusBadge status={ticket.status} /><TicketPriorityBadge priority={ticket.priority} />{ticket.is_overdue && ticket.status !== "COMPLETED" && ticket.status !== "CANCELLED" ? <span className="inline-flex items-center gap-1 rounded-full border border-red-300 bg-red-50 px-2.5 py-1 text-xs font-bold text-red-800"><span aria-hidden="true">!</span>Atrasada{ticket.overdue_seconds ? ` · ${formatOverdue(ticket.overdue_seconds)}` : ""}</span> : null}</div><h2 className="mt-4 line-clamp-2 text-base font-bold text-slate-950">{ticket.title}</h2>{ticket.description ? <p className="mt-1 line-clamp-2 text-sm text-slate-600">{ticket.description}</p> : null}<dl className="mt-4 grid gap-3 text-sm"><div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">Categoria</dt><dd className="mt-0.5 text-slate-800">{ticket.category}</dd></div>{showRequester ? <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">Solicitante</dt><dd className="mt-0.5 text-slate-800">{ticket.requester}</dd></div> : null}<div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">Prazo</dt><dd className={`mt-0.5 font-medium ${ticket.is_overdue ? "text-red-700" : "text-slate-800"}`}>{formatDueDate(ticket.due_date)}</dd></div>{ticket.created_at ? <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">Criada em</dt><dd className="mt-0.5 text-slate-800">{formatDateTime(ticket.created_at)}</dd></div> : null}</dl><div className="mt-5 border-t border-slate-100 pt-4"><TicketAssignee assignee={ticket.assignee} /></div>{action ? <div className="mt-4">{action}</div> : null}</article>;
}
import type { ReactNode } from "react";
